version: "2"

options:
  compose-file-path: './docker-compose.yml'
  compose-dev-file-path: './docker-compose-mac.yml'
  verbose: false
syncs:
  vovinam-front-sync:
    src: '../../frontend/.'
    host_disk_mount_mode: 'cached'
    sync_excludes: ['node_modules']
  vovinam-admin-sync:
    src: '../../drupal/.'
    host_disk_mount_mode: 'cached'
